import { samplePathAtT } from '../scene/paths.js';
import { propBounds } from '../proxies/registry.js';

// Export Blender.
//
// On genere un script Python autonome qui reconstruit le blocking : decor,
// proxys, et surtout la camera et les acteurs animes image par image.
//
// Conversion de repere : three.js est Y-up (x, y, z) ; Blender est Z-up.
//   blender(X, Y, Z) = three(x, -z, y)
// Les cles sont donc converties a l'export, jamais dans Blender.

const n = (v) => Number(v.toFixed(4));

/**
 * Les fonctions build() ecrites par gpt-6-astra sont renommees et reindentees
 * pour cohabiter dans un seul fichier, puis appelees a la place de la primitive
 * generique. Une entite sans modele garde son volume de blocking.
 */
function aiBuilders(scene) {
  const models = scene.models || {};
  const blocks = [];
  const byEntity = {};
  let i = 0;

  for (const [entityId, entry] of Object.entries(models)) {
    if (!entry?.blender) continue;
    i += 1;
    const fnName = `ai_build_${i}`;
    const src = entry.blender.replace(/^\s*def\s+build\s*\(/m, `def ${fnName}(`);
    blocks.push(`# --- generated by gpt-6-astra for "${entityId}" ---
${src}`);
    byEntity[entityId] = fnName;
  }
  return { blocks, byEntity };
}

/** three (x, y, z) -> blender (X, Y, Z) */
const toBlender = (p) => [n(p.x), n(-p.z), n(p.y)];

/**
 * Cap orientation : dans Blender le proxy pointe son +Y local vers l'avant.
 * Apres rotation de theta autour de Z, +Y vaut (-sin, cos) ; on veut
 * (sin(yaw), -cos(yaw)), d'ou theta = yaw + pi.
 */
const yawToBlender = (yaw) => n(yaw + Math.PI);

function aabbToBlender(c) {
  // Un AABB three devient une boite Blender : centre converti, dimensions
  // permutees (la profondeur three devient la profondeur Blender sur Y).
  const cx = (c.min[0] + c.max[0]) / 2;
  const cy = (c.min[1] + c.max[1]) / 2;
  const cz = (c.min[2] + c.max[2]) / 2;
  return {
    name: c.name,
    kind: c.kind,
    loc: [n(cx), n(-cz), n(cy)],
    dim: [n(c.max[0] - c.min[0]), n(c.max[2] - c.min[2]), n(c.max[1] - c.min[1])],
  };
}

const hexToRgb = (hex) => {
  const h = String(hex).replace('#', '');
  return [
    n(parseInt(h.slice(0, 2), 16) / 255),
    n(parseInt(h.slice(2, 4), 16) / 255),
    n(parseInt(h.slice(4, 6), 16) / 255),
  ];
};

const py = (v) => JSON.stringify(v);

// Separateur des fonctions generees, isole pour ne pas casser le template.
const SEP = String.fromCharCode(10, 10);

/**
 * @param {object} scene SceneGraph normalise
 * @param {object} solve resultat de solveScene
 * @returns {string} script Python pret a coller dans Blender
 */
export function buildBlenderScript(scene, solve) {
  const { project, camera } = scene;
  const frameCount = solve.track.frames.length;
  const fps = project.fps;
  const ai = aiBuilders(scene);

  // --- Acteurs : une cle par image ---------------------------------------
  const actors = scene.actors.map((actor) => {
    const entry = solve.actorPaths.get(actor.id);
    const keys = [];
    for (let f = 0; f < frameCount; f += 1) {
      const t01 = frameCount > 1 ? f / (frameCount - 1) : 0;
      const { position, tangent } = samplePathAtT(entry.path, t01);
      const [X, Y, Z] = toBlender(position);
      keys.push([X, Y, Z, yawToBlender(Math.atan2(tangent.x, tangent.z))]);
    }
    return {
      name: actor.name,
      builder: ai.byEntity[actor.id] || null,
      color: hexToRgb(actor.color),
      height: n(actor.height),
      radius: n(actor.height * 0.145),
      keys,
    };
  });

  // --- Camera : position + point vise, une cle par image ------------------
  const camKeys = solve.track.frames.map((f) => toBlender(f.position));
  const targetKeys = solve.track.frames.map((f) => toBlender(f.lookAt));

  const zones = scene.zones.map((z) => ({
    name: z.name,
    color: hexToRgb(z.color),
    loc: [n(z.position[0]), n(-z.position[2]), n(z.position[1])],
    dim: [n(z.width), n(z.depth)],
  }));

  const walls = solve.colliders.filter((c) => c.kind !== 'prop').map(aabbToBlender);

  const props = (scene.props || []).map((p) => {
    const b = propBounds(p);
    return {
      name: p.name,
      builder: ai.byEntity[p.id] || null,
      type: b.type,
      color: hexToRgb(p.color),
      loc: [n(p.position[0]), n(-p.position[2]), 0],
      dim: [n(b.width), n(b.depth), n(b.height)],
      rot: n(-(p.rotation || 0)),
    };
  });

  const [aw, ah] = String(project.aspectRatio).match(/(\d+(?:\.\d+)?)\D+(\d+(?:\.\d+)?)/)
    ? String(project.aspectRatio)
        .match(/(\d+(?:\.\d+)?)\D+(\d+(?:\.\d+)?)/)
        .slice(1, 3)
        .map(Number)
    : [16, 9];
  const resX = 1920;
  const resY = Math.round((resX * ah) / aw);

  return `# ${'-'.repeat(72)}
# BLOCKING.3D -> Blender
# Scene    : ${project.name}
# Duration : ${project.duration}s @ ${fps} fps (${frameCount} frames)
# Camera   : ${camera.rig}, ${camera.lens}mm, height ${camera.height}m${
    camera.keys ? ` (${camera.keys.length} authored keys)` : ''
  }
#
# Usage: open Blender > Scripting tab > New > paste > Run Script.
# Everything is created inside a "BLOCKING_3D" collection, so your existing
# scene is left untouched.
#
# Axis conversion is already applied (three.js Y-up -> Blender Z-up).
# Actors and camera are baked one keyframe per frame, so the motion matches
# the browser preview exactly.
# Props are blocking volumes: replace them with real assets when you dress
# the set. The camera animation is the part you want to keep.
# ${'-'.repeat(72)}

import bpy
import math
from mathutils import Vector

FPS = ${fps}
FRAME_COUNT = ${frameCount}
COLLECTION = "BLOCKING_3D"

ZONES = ${py(zones)}
WALLS = ${py(walls)}
PROPS = ${py(props)}
ACTORS = ${py(actors)}
CAM_KEYS = ${py(camKeys)}
TARGET_KEYS = ${py(targetKeys)}

CAM_LENS = ${n(camera.lens)}
SENSOR_HEIGHT = 24.0  # matches the 35mm full-frame convention used in the app


# --- housekeeping ---------------------------------------------------------

def fresh_collection(name):
    """Remove a previous run and start from a clean collection."""
    existing = bpy.data.collections.get(name)
    if existing:
        for obj in list(existing.objects):
            bpy.data.objects.remove(obj, do_unlink=True)
        bpy.data.collections.remove(existing)
    col = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(col)
    return col


def material(name, rgb, alpha=1.0):
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
        if "Roughness" in bsdf.inputs:
            bsdf.inputs["Roughness"].default_value = 0.75
        if alpha < 1.0:
            bsdf.inputs["Alpha"].default_value = alpha
            mat.blend_method = 'BLEND'
    return mat


def put(obj, col, mat=None):
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    col.objects.link(obj)
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def add_box(name, loc, dim, col, mat, rot_z=0.0):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=loc)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = (dim[0], dim[1], dim[2])
    obj.rotation_euler[2] = rot_z
    return put(obj, col, mat)


def add_cylinder(name, loc, radius, depth, col, mat):
    bpy.ops.mesh.primitive_cylinder_add(radius=radius, depth=depth, location=loc, vertices=16)
    obj = bpy.context.active_object
    obj.name = name
    return put(obj, col, mat)


# --- AI-generated geometry -------------------------------------------------
# Written by gpt-6-astra from the object description and the blocking bounding
# box. Each function returns the objects it creates, in local space.
${ai.blocks.length ? ai.blocks.join(SEP) : '# (none - every element uses its generic blocking volume)'}


def place(objs, col, loc, rot_z=0.0):
    """Parent AI-generated parts to an empty and drop them at their world spot."""
    root = bpy.data.objects.new("AI_ROOT", None)
    root.empty_display_size = 0.2
    col.objects.link(root)
    root.location = loc
    root.rotation_euler[2] = rot_z
    for o in objs:
        for c in list(o.users_collection):
            c.objects.unlink(o)
        col.objects.link(o)
        o.parent = root
    return root


# --- build ----------------------------------------------------------------

col = fresh_collection(COLLECTION)

scene = bpy.context.scene
scene.render.fps = FPS
scene.frame_start = 1
scene.frame_end = FRAME_COUNT
scene.render.resolution_x = ${resX}
scene.render.resolution_y = ${resY}

# Floors
for z in ZONES:
    bpy.ops.mesh.primitive_plane_add(size=1.0, location=(z["loc"][0], z["loc"][1], z["loc"][2] + 0.001))
    obj = bpy.context.active_object
    obj.name = "ZONE_" + z["name"]
    obj.scale = (z["dim"][0], z["dim"][1], 1.0)
    put(obj, col, material("zone_" + z["name"], z["color"]))

# Walls, lintels and door jambs (these are the actual collision volumes)
wall_mat = material("blocking_wall", [0.19, 0.21, 0.24], alpha=0.55)
door_mat = material("blocking_doorframe", [0.35, 0.37, 0.41])
for w in WALLS:
    add_box(
        ("DOOR_" if w["kind"] == "doorframe" else "WALL_") + w["name"],
        w["loc"], w["dim"], col,
        door_mat if w["kind"] == "doorframe" else wall_mat,
    )

# Props (blocking volumes)
for p in PROPS:
    mat = material("prop_" + p["name"], p["color"])
    base = (p["loc"][0], p["loc"][1], p["dim"][2] / 2.0)
    if p.get("builder"):
        # Geometrie ecrite par gpt-6-astra pour cet objet precis.
        place(globals()[p["builder"]]("PROP_" + p["name"], mat), col,
              (p["loc"][0], p["loc"][1], 0.0), p["rot"])
    elif p["type"] in ("car", "truck"):
        # Chassis + offset cabin + wheels, so the silhouette reads as a vehicle.
        body_h = p["dim"][2] * 0.45
        add_box("PROP_" + p["name"], (base[0], base[1], body_h / 2.0),
                (p["dim"][0], p["dim"][1], body_h), col, mat, p["rot"])
        add_box("PROP_" + p["name"] + "_cabin",
                (base[0], base[1] - p["dim"][1] * 0.06, body_h + p["dim"][2] * 0.22),
                (p["dim"][0] * 0.88, p["dim"][1] * 0.46, p["dim"][2] * 0.4), col, mat, p["rot"])
        r = p["dim"][2] * 0.22
        for sx in (-1, 1):
            for sy in (-1, 1):
                bpy.ops.mesh.primitive_cylinder_add(
                    radius=r, depth=r * 0.7, vertices=12,
                    location=(base[0] + sx * p["dim"][0] * 0.42,
                              base[1] + sy * p["dim"][1] * 0.31, r),
                    rotation=(0, math.pi / 2, p["rot"]),
                )
                wheel = bpy.context.active_object
                wheel.name = "PROP_" + p["name"] + "_wheel"
                put(wheel, col, material("wheel", [0.08, 0.09, 0.11]))
    elif p["type"] == "tree":
        add_cylinder("PROP_" + p["name"] + "_trunk",
                     (base[0], base[1], p["dim"][2] * 0.28),
                     p["dim"][0] * 0.09, p["dim"][2] * 0.56, col,
                     material("bark", [0.29, 0.23, 0.16]))
        bpy.ops.mesh.primitive_uv_sphere_add(radius=p["dim"][0] * 0.46,
                                             location=(base[0], base[1], p["dim"][2] * 0.7))
        canopy = bpy.context.active_object
        canopy.name = "PROP_" + p["name"] + "_canopy"
        put(canopy, col, mat)
    else:
        add_box("PROP_" + p["name"], base, p["dim"], col, mat, p["rot"])

# Actors: cylinder + head, baked one keyframe per frame
for a in ACTORS:
    mat = material("actor_" + a["name"], a["color"])
    body_h = a["height"] * 0.8
    root = bpy.data.objects.new("ACTOR_" + a["name"], None)
    root.empty_display_size = 0.3
    col.objects.link(root)

    if a.get("builder"):
        # Geometrie ecrite par gpt-6-astra pour ce personnage.
        parts = globals()[a["builder"]]("ACTOR_" + a["name"], mat)
        for o in parts:
            for c in list(o.users_collection):
                c.objects.unlink(o)
            col.objects.link(o)
    else:
        body = add_cylinder("ACTOR_" + a["name"] + "_body", (0, 0, body_h / 2.0),
                            a["radius"], body_h, col, mat)
        bpy.ops.mesh.primitive_uv_sphere_add(radius=a["height"] * 0.085,
                                             location=(0, 0, body_h + a["height"] * 0.077))
        head = bpy.context.active_object
        head.name = "ACTOR_" + a["name"] + "_head"
        put(head, col, mat)
        # Small nose along local +Y so the facing direction is readable.
        bpy.ops.mesh.primitive_cone_add(radius1=a["height"] * 0.045, depth=a["height"] * 0.13,
                                        vertices=8, location=(0, a["radius"] * 0.9, a["height"] * 0.66),
                                        rotation=(-math.pi / 2, 0, 0))
        nose = bpy.context.active_object
        nose.name = "ACTOR_" + a["name"] + "_nose"
        put(nose, col, mat)
        parts = (body, head, nose)

    for child in parts:
        child.parent = root

    for i, k in enumerate(a["keys"]):
        root.location = (k[0], k[1], k[2])
        root.rotation_euler = (0.0, 0.0, k[3])
        root.keyframe_insert("location", frame=i + 1)
        root.keyframe_insert("rotation_euler", frame=i + 1)

    for fc in root.animation_data.action.fcurves:
        for kp in fc.keyframe_points:
            kp.interpolation = 'LINEAR'

# Camera: aimed with a TRACK_TO constraint on an animated empty.
target = bpy.data.objects.new("CAM_TARGET", None)
target.empty_display_size = 0.2
col.objects.link(target)

cam_data = bpy.data.cameras.new("BLOCKING_CAM")
cam_data.sensor_fit = 'VERTICAL'
cam_data.sensor_height = SENSOR_HEIGHT
cam_data.lens = CAM_LENS
cam_data.clip_start = 0.05
cam_data.clip_end = 400.0
cam = bpy.data.objects.new("BLOCKING_CAM", cam_data)
col.objects.link(cam)

track = cam.constraints.new(type='TRACK_TO')
track.target = target
track.track_axis = 'TRACK_NEGATIVE_Z'
track.up_axis = 'UP_Y'

for i, (c, t) in enumerate(zip(CAM_KEYS, TARGET_KEYS)):
    cam.location = Vector(c)
    target.location = Vector(t)
    cam.keyframe_insert("location", frame=i + 1)
    target.keyframe_insert("location", frame=i + 1)

for obj in (cam, target):
    for fc in obj.animation_data.action.fcurves:
        for kp in fc.keyframe_points:
            kp.interpolation = 'LINEAR'

scene.camera = cam
scene.frame_set(1)

print("BLOCKING.3D: imported '${project.name.replace(/'/g, "\\'")}' "
      "-- %d frames, %d actors, %d props." % (FRAME_COUNT, len(ACTORS), len(PROPS)))
`;
}
