import { describe, it, expect } from 'vitest';
import street from '../fixtures/street.json';
import { normalizeSceneGraph } from '../scene/normalize.js';
import { solveScene } from '../scene/build.js';
import { buildBlenderScript } from '../export/blender.js';
import { compileModel, instantiateModel } from './AIModel.jsx';

const GOOD = `
function build(THREE, color) {
  const g = new THREE.Group();
  const mat = new THREE.MeshStandardMaterial({ color, flatShading: true });
  const body = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), mat);
  body.position.y = 0.5;
  g.add(body);
  return g;
}
`;

describe('compilation des modeles IA', () => {
  it('accepte une fonction build() valide', () => {
    const r = compileModel(GOOD);
    expect(r.ok).toBe(true);
    expect(typeof r.build).toBe('function');
  });

  it('refuse un code sans build()', () => {
    const r = compileModel('const x = 1;');
    expect(r.ok).toBe(false);
    expect(r.error).toMatch(/build\(\)/);
  });

  it.each([
    ['fetch', 'function build(){ fetch("http://x"); }'],
    ['document', 'function build(){ document.body.innerHTML = ""; }'],
    ['import', 'import fs from "fs"; function build(){}'],
    ['eval', 'function build(){ eval("1"); }'],
    ['localStorage', 'function build(){ localStorage.clear(); }'],
  ])('refuse le motif interdit %s', (_label, src) => {
    const r = compileModel(src);
    expect(r.ok).toBe(false);
    expect(r.error).toMatch(/motif interdit/);
  });

  it('ne laisse pas une erreur d\'execution remonter', () => {
    const r = instantiateModel('function build(){ throw new Error("boom"); }', '#ffffff', null);
    expect(r.ok).toBe(false);
    expect(r.error).toMatch(/boom/);
  });
});

describe('respect du gabarit', () => {
  it('remet un modele hors gabarit a l\'echelle imposee', () => {
    // Le modele fait 1 m de cote ; le gabarit vise 4 m de large.
    const bounds = { width: 4, height: 4, depth: 4 };
    const r = instantiateModel(GOOD, '#F27D26', bounds);
    expect(r.ok).toBe(true);
    expect(r.group.scale.x).toBeCloseTo(4, 2);
  });

  it('repose le modele au sol', () => {
    const floating = `
      function build(THREE, color) {
        const g = new THREE.Group();
        const m = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1),
          new THREE.MeshStandardMaterial({ color }));
        m.position.y = 5; // le modele oublie la contrainte y >= 0
        g.add(m);
        return g;
      }`;
    const r = instantiateModel(floating, '#F27D26', { width: 1, height: 1, depth: 1 });
    expect(r.ok).toBe(true);
    // Apres recalage, le bas du modele touche y = 0.
    expect(r.group.position.y).toBeCloseTo(-4.5, 2);
  });
});

describe('injection dans l\'export Blender', () => {
  const AI_PY = `def build(name, mat):
    objs = []
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0.5))
    o = bpy.context.active_object
    o.name = name + "_body"
    o.data.materials.append(mat)
    objs.append(o)
    return objs
`;

  const withModel = () => {
    const { scene } = normalizeSceneGraph({
      ...street,
      models: { prop_1: { blender: AI_PY, three: GOOD } },
    });
    return { scene, solve: solveScene(scene) };
  };

  it('renomme la fonction generee et l\'appelle pour le bon objet', () => {
    const { scene, solve } = withModel();
    const py = buildBlenderScript(scene, solve);
    expect(py).toContain('def ai_build_1(name, mat):');
    expect(py).toContain('generated by gpt-6-astra for "prop_1"');
    expect(py).toContain('globals()[p["builder"]]');
    const props = JSON.parse(py.match(/PROPS = (\[.*?\])\nACTORS/s)[1]);
    expect(props.find((p) => p.name === 'Parked Car').builder).toBe('ai_build_1');
    expect(props.find((p) => p.name === 'Delivery Truck').builder).toBeNull();
  });

  it('conserve les volumes de blocking pour les objets non modelises', () => {
    const { scene, solve } = withModel();
    const py = buildBlenderScript(scene, solve);
    // La branche primitive doit rester : tout n'est pas modelise par l'IA.
    expect(py).toContain('elif p["type"] in ("car", "truck"):');
  });

  it('signale l\'absence de modele quand il n\'y en a aucun', () => {
    const { scene } = normalizeSceneGraph(street);
    const py = buildBlenderScript(scene, solveScene(scene));
    expect(py).toContain('# (none - every element uses its generic blocking volume)');
  });
});
